### ISSUE TITLE
Issue while building in eclipse

### ISSUE THREAD

**Issue by viswajakkam** [milanaleksic/gradle-multiplatform-plugin#1]
Facing the below issue while buidling.

> No such property: s3AccessKey for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

Any help will be appreciated.

Thanks
Jakkam

**Comment by milanaleksic** [comment]
This should be fixed with commit https://github.com/milanaleksic/gradle-multiplatform-plugin/commit/3d760932f35850eb45da500c4397933e35ac3a8d (I had it only in the ~/gradle.properties, not in this inside project, sorry about that)
